home/urls.py
from django.urls import path

from . import views

urlpatterns = [
    # ex: /home/
    path('', views.index, name='index'),


    # ex: /home/5/
    #path('<int:question_id>/', views.detail, name='detail'),
]

mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from home import views

urlpatterns = [
    path('', include('home.urls')),
    path('home/', include('home.urls')),
    path('product/', include('product.urls')),
    path('user/', include('user.urls')),
    path('content/', include('content.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('admin/', admin.site.urls),

    path('hakkimizda/', views.hakkimizda, name='hakkimizda'),
    path('referanslar/', views.referanslar, name='referanslar'),
    path('iletisim/', views.iletisim, name='iletisim'),
    path('search/', views.product_search, name='product_search'),
    path('search_auto/', views.product_search_auto, name='product_search_auto'),
    path('logout/', views.logout_view, name='logout_view'),
    path('login/', views.login_view, name='login_view'),
    path('signup/', views.signup_view, name='signup_view'),
    path('error/', views.error, name='error'),
    path('sss/', views.faq, name='faq'),

    path('category/<int:id>/<slug:slug>/', views.category_products, name='category_products'),
    path('product/<int:id>/<slug:slug>/', views.product_detail, name='product_detail'),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path

from user import views

urlpatterns = [
    # ex: /home/
    path('', views.index, name='index'),
    path('update/', views.user_update, name='user_update'),
    path('password/', views.change_password, name='change_password'),
    path('comments/', views.comments, name='comments'),
    path('deletecomment/<int:id>', views.deletecomment, name='deletecomment'),
    path('addcontent/', views.addcontent, name='addcontent'),
    path('contents/', views.contents, name='contents'),
    path('contentedit/<int:id>', views.contentedit, name='contentedit'),
    path('contentdelete/<int:id>', views.contentdelete, name='contentdelete'),
    path('contentaddimage/<int:id>', views.contentaddimage, name='contentaddimage'),


    #path('addcomment/<int:id>', views.addcomment, name='addcomment')


    # ex: /home/5/
    #path('<int:question_id>/', views.detail, name='detail'),
]

home/models.py
from ckeditor_uploader.fields import RichTextUploadingField
from django.contrib.auth.models import User
from django.db import models

# Create your models here.
from django.forms import ModelForm, TextInput, Textarea
from django.utils.safestring import mark_safe


class Setting(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır')
    )
    title = models.CharField(max_length=150)
    keywords = models.CharField(max_length=255)
    description = models.CharField(max_length=255)
    company = models.CharField(max_length=50)
    address = models.CharField(max_length=150)
    phone = models.CharField(blank=True, max_length=15)
    fax = models.CharField(blank=True, max_length=15)
    email = models.CharField(blank=True, max_length=50)
    smtpserver = models.CharField(blank=True, max_length=20)
    smtpemail = models.CharField(blank=True, max_length=20)
    smtppassword = models.CharField(blank=True, max_length=10)
    smtpport = models.CharField(blank=True, max_length=5)
    icon = models.ImageField(blank=True, upload_to='images/')
    facebook = models.CharField(blank=True, max_length=50)
    instagram = models.CharField(blank=True, max_length=50)
    twitter = models.CharField(blank=True, max_length=50)
    abouts = RichTextUploadingField(blank=True)
    contact = RichTextUploadingField(blank=True)
    references = RichTextUploadingField(blank=True)
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.title


class ContactFormMessage(models.Model):
    STATUS = (
        ('New', 'New'),
        ('Read', 'Read'),
        ('Closed', 'Closed'),
    )
    name = models.CharField(blank=True, max_length=20)
    email = models.CharField(blank=True, max_length=50)
    subject = models.CharField(blank=True, max_length=50)
    message = models.CharField(blank=True, max_length=255)
    status = models.CharField(max_length=10, choices=STATUS, default='New')
    ip = models.CharField(blank=True, max_length=20)
    note = models.CharField(blank=True, max_length=100)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name


class ContactForm(ModelForm):
    class Meta:
        model = ContactFormMessage
        fields = ['name', 'email', 'subject', 'message']


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone = models.CharField(blank=True, max_length=20)
    address = models.CharField(blank=True, max_length=150)
    city = models.CharField(blank=True, max_length=20)
    country = models.CharField(blank=True, max_length=20)
    image = models.ImageField(blank=True, upload_to='images/users/')

    def __str__(self):
        return self.user.username

    def user_name(self):
        return  self.user.first_name + ' ' + self.user.last_name + ' [' + self.user.username + ']'

    def image_tag(self):
        return mark_safe('<img src="{}" height="50"/>'.format(self.image.url))
    image_tag.short_description = 'Image'


class UserProfileForm(ModelForm):
    class Meta:
        model = UserProfile
        fields = ['phone', 'address', 'city', 'country', 'image']


class FAQ(models.Model):
    STATUS = (
        ('True', 'Evet'),
        ('False', 'Hayır')
    )
    ordernumber = models.IntegerField()
    question = models.CharField(max_length=150)
    answer = models.TextField()
    status = models.CharField(max_length=10, choices=STATUS)
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.question

user/models.py
from django.db import models

# Create your models here.

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django.contrib.auth.models import User
from django.forms import TextInput, EmailInput, Select, FileInput

from home.models import UserProfile


class UserUpdateForm(UserChangeForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name')
        widgets = {
            'username': TextInput(attrs={'class': 'input', 'placeholder': 'username'}),
            'email': EmailInput(attrs={'class': 'input', 'placeholder': 'email'}),
            'first_name': TextInput(attrs={'class': 'input', 'placeholder': 'first_name'}),
            'last_name': TextInput(attrs={'class': 'input', 'placeholder': 'last_name'}),
        }


CITY = [
    ('Istanbul', 'Istanbul'),
    ('Ankara', 'Ankara'),
    ('Izmir', 'Izmir')
]


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('phone', 'address', 'city', 'country', 'image')
        widgets = {
            'phone': TextInput(attrs={'class': 'input', 'placeholder': 'phone'}),
            'address': TextInput(attrs={'class': 'input', 'placeholder': 'address'}),
            'city': Select(attrs={'class': 'input', 'placeholder': 'city'}, choices=CITY),
            'country': TextInput(attrs={'class': 'input', 'placeholder': 'country'}),
            'image': FileInput(attrs={'class': 'input', 'placeholder': 'image'}),
        }

user/views.py
from django.contrib import messages
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import PasswordChangeForm
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect

from content.models import Content, CImages
from home.models import UserProfile, ContactForm
from product.models import Category, Comment, ContentForm, Product, ContentImageForm, Images
from user.forms import UserUpdateForm, ProfileUpdateForm


def index(request):
    category = Category.objects.all()
    current_user = request.user
    profile = UserProfile.objects.get(user_id=current_user.id)
    context = {'category': category,
               'profile': profile, }
    return render(request, 'user_profile.html', context)


@login_required(login_url='/login')
def user_update(request):
    if request.method == 'POST':
        user_form = UserUpdateForm(request.POST, instance=request.user)
        profile_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.userprofile)
        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()
            messages.success(request, "Your account has been updated!")
            return redirect('/user')
    else:
        category = Category.objects.all()
        user_form = UserUpdateForm(instance=request.user)
        profile_form = ProfileUpdateForm(instance=request.user.userprofile)
        context = {'category': category,
                   'user_form': user_form,
                   'profile_form': profile_form, }
        return render(request, 'user_update.html', context)


@login_required(login_url='/login')
def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(request.user, request.POST)
        if form.is_valid():
            user = form.save()
            update_session_auth_hash(request, user)
            messages.success(request, 'Your password was successfully updated!')
            return redirect('change_password')
        else:
            messages.error(request, 'Please correct the error bellow.<br>' + str(form.errors))
            return HttpResponseRedirect('/user/password')
    else:
        category = Category.objects.all()
        form = PasswordChangeForm(request.user)
        return render(request, 'change_password.html', {
            'form': form, 'category': category
        })


@login_required(login_url='/login')
def comments(request):
    category = Category.objects.all()
    current_user = request.user
    comments = Comment.objects.filter(user_id=current_user.id)
    context = {'category': category,
               'comments': comments, }
    return render(request, 'user_comments.html', context)


@login_required(login_url='/login')
def deletecomment(request, id):
    current_user = request.user
    Comment.objects.filter(id=id, user_id=current_user.id).delete()
    messages.success(request, 'Comment deleted!')
    return HttpResponseRedirect('/user/comments')


@login_required(login_url='/login')
def contents(request):
    category = Category.objects.all()
    current_user = request.user
    contents = Product.objects.filter(user_id=current_user.id)
    context = {'category': category,
               'contents': contents}
    return render(request, 'user_contents.html', context)


@login_required(login_url='/login')
def addcontent(request):
    if request.method == 'POST':
        form = ContentForm(request.POST, request.FILES)
        if form.is_valid():
            current_user = request.user
            data = Product()
            data.user_id = current_user.id
            #data.category_id =
            data.title = form.cleaned_data['title']
            data.keywords = form.cleaned_data['keywords']
            data.description = form.cleaned_data['description']
            data.image = form.cleaned_data['image']
            #data.type = form.cleaned_data['type']
            data.slug = form.cleaned_data['slug']
            data.detail = form.cleaned_data['detail']
            data.status = 'False'
            data.save()
            messages.success(request, 'Blog added!')
            return HttpResponseRedirect('/user/contents')
        else:
            messages.warning(request, 'Content form error :'+str(form.errors))
            return HttpResponseRedirect('/user/addcontent')
    else:
        category = Category.objects.all()
        form = ContentForm()
        context = {'category': category,
                   'form': form}
        return render(request, 'user_addcontents.html', context)


@login_required(login_url='/login')
def contentedit(request, id):
    content = Product.objects.get(id=id)
    if request.method == 'POST':
        form = ContentForm(request.POST, request.FILES, instance=content)
        if form.is_valid():
            form.save()
            messages.success(request, 'Blog updated successfully!')
            return HttpResponseRedirect('/user/contents')
        else:
            messages.success(request, 'Content form error :'+str(form.errors))
            return HttpResponseRedirect('/user/contentedit'+str(id))
    else:
        category = Category.objects.all()
        form = ContentForm(instance=content)
        context = {'category': category,
                   'form': form}
        return render(request, 'user_addcontents.html', context)


@login_required(login_url='/login')
def contentdelete(request, id):
    current_user = request.user
    Product.objects.filter(id=id, user_id=current_user.id).delete()
    messages.success(request, 'Blog deleted!')
    return HttpResponseRedirect('/user/contents')


def contentaddimage(request, id):
    if request.method == 'POST':
        lasturl = request.META.get('HTTP_REFERER')
        form = ContentImageForm(request.POST, request.FILES)
        if form.is_valid():
            data = Images()
            data.title = form.cleaned_data['title']
            data.product_id = id
            data.image = form.cleaned_data['image']
            data.save()
            messages.success(request, 'Your image has been successfully uploaded!')
            return HttpResponseRedirect(lasturl)
        else:
            messages.warning(request, 'Form error :' + str(form.errors))
            return HttpResponseRedirect(lasturl)
    else:
        content = Product.objects.get(id=id)
        images = Images.objects.filter(product_id=id)
        form = ContentImageForm()
        context = {'content': content,
                   'form': form,
                   'images': images}
        return render(request, 'content_gallery.html', context)

user/templates/change_password.html
{% extends "homebase.html" %}

{% block title %}{{ profile.user_name }} Profile{% endblock %}
{% block keywords %}{{ setting.keywords }}{% endblock %}
{% block description %}{{ setting.description }}{% endblock %}
{% block head %}
    <link rel="shortcut icon" type="image/x-icon" href="{{ setting.icon.url }}"/>
{% endblock %}


{% block content %}
    <div class="section">
        <div class="container">
            <div class="row mb-4">
                <div class="col-md-6">
                    <h1>User Profile</h1>
                </div>
            </div>

            <div class="row blog-entries">

                {% include "user_panel.html" %}

                <div class="col-md-9 ">

                    {% if messages %}
                        {% for message in messages %}
                            <div style="color: #d43f3a; font-size: medium">
                            {{ message|safe }}
                            </div>
                        {% endfor %}
                    {% endif %}
                        <form method="post">
                            {% csrf_token %}
                            {% for field in form %}
                                <p>
                                    {{ field.label_tag }}<br>
                                    {{ field }}
                                    {% if field.help_text %}
                                        <small style="color: grey">{{ field.help_text }}</small>
                                    {% endif %}
                                    {% for error in field.errors %}
                                        <p style="color: red">{{ error }}</p>
                                    {% endfor %}
                                </p>
                            {% endfor %}
                            <div class="form-group">
                                <button class="btn btn-danger" type="submit">Update</button>
                            </div>
                        </form>

                </div>
            </div>

        </div>
    </div>
    </div>
{% endblock %}





{% comment %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Deneme</title>
</head>
<body>
    <h2>Django kurulum : python -m pip install</h2>
    <h2>Proje oluşturma : django-admin startproject mysite</h2>
    <h2>Server çalıştırma : python manage.py runserver</h2>
    <h2>App ekleme : python manage.py startapp home</h2>
    echo "# DjangoBlog" >> README.md
git init  //Bir kez
git add README.md   //Bir kez
git add .       //Her güncellemede
git commit -m "first commit"   //Her güncellemede
git remote add origin https://github.com/altuntasfth/DjangoBlog.git     //Bir kez
git push -u origin master    //Her güncellemede
git remote add origin https://github.com/altuntasfth/DjangoBlog.git
git push -u origin master
    <p>{{ text }}</p>
</body>
</html>{% endcomment %}

user/templates/content_gallery.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Content Gallery</title>
</head>
<body>
    <h2>{{ content.title }}</h2>
    <hr>
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}" role="alert">
                {{ message|safe }}
            </div>
        {% endfor %}
    {% endif %}

    <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
        <input type="hidden" name="content_id" id="id_content_id" value="{{ product.id }}">
        <label for="id_title">Title:</label>
        <input type="text" name="title" class="input_number" placeholder="title" maxlength="50" id="id_title">
        <label for="id_image">Image:</label>
        <input type="file" name="image" class="input_number" placeholder="image" accept="image/*" id="id_image">
        <button class="btn-primary" type="submit">Upload Image</button>
    </form>

    <hr>
    <h4>Yüklenen Resimler</h4>
    {% for rs in images %}
        <img src="{{ rs.image.url }}" height="200">
     {% endfor %}
</body>
</html>

user/templates/user_addcontents.html
{% extends "homebase.html" %}

{% block title %}{{ profile.user_name }} Profile{% endblock %}
{% block keywords %}{{ setting.keywords }}{% endblock %}
{% block description %}{{ setting.description }}{% endblock %}
{% block head %}
    <link rel="shortcut icon" type="image/x-icon" href="{{ setting.icon.url }}"/>
    {% load static %}
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.2.4/jquery.min.js"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
    <script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
{% endblock %}


{% block content %}
    <div class="section">
        <div class="container">
            <div class="row mb-4">
                <div class="col-md-6">
                    <h1>User Comments</h1>
                </div>
            </div>

            <div class="row blog-entries">
                <div class="col-md-2">
                    {% include "user_panel.html" %}
                </div>
                <div class="col-md-10 ">

                    <form method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <fieldset class="form-group">
                            {{ form.media }}
                            {{ form.as_p }}
                        </fieldset>
                        <div class="form-group">
                            <button class="btn btn-primary" type="submit">SAVE</button>
                        </div>
                    </form>

                </div>
            </div>

        </div>
    </div>
    </div>
{% endblock %}





{% comment %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Deneme</title>
</head>
<body>
    <h2>Django kurulum : python -m pip install</h2>
    <h2>Proje oluşturma : django-admin startproject mysite</h2>
    <h2>Server çalıştırma : python manage.py runserver</h2>
    <h2>App ekleme : python manage.py startapp home</h2>
    echo "# DjangoBlog" >> README.md
git init  //Bir kez
git add README.md   //Bir kez
git add .       //Her güncellemede
git commit -m "first commit"   //Her güncellemede
git remote add origin https://github.com/altuntasfth/DjangoBlog.git     //Bir kez
git push -u origin master    //Her güncellemede
git remote add origin https://github.com/altuntasfth/DjangoBlog.git
git push -u origin master
    <p>{{ text }}</p>
</body>
</html>{% endcomment %}

user/templates/user_comments.html
{% extends "homebase.html" %}

{% block title %}{{ profile.user_name }} Profile{% endblock %}
{% block keywords %}{{ setting.keywords }}{% endblock %}
{% block description %}{{ setting.description }}{% endblock %}
{% block head %}
    <link rel="shortcut icon" type="image/x-icon" href="{{ setting.icon.url }}"/>
{% endblock %}


{% block content %}
    <div class="section">
        <div class="container">
            <div class="row mb-4">
                <div class="col-md-6">
                    <h1>User Comments</h1>
                </div>
            </div>

            <div class="row blog-entries">
                <div class="col-md-2">
                    {% include "user_panel.html" %}
                </div>
                <div class="col-md-10 ">

                    <table class="table-active table">
                        <tr>
                            <th class="text-left">Blog</th>
                            <th class="text-left">Comment</th>
                            <th class="text-left">Status</th>
                            <th class="text-left">Date</th>
                        </tr>
                        {% for rs in comments %}
                            <tr>
                                <td class="text-left">
                                    <a href="/product/{{ rs.product_id }}/{{ rs.product.slug }}">
                                        <b>{{ rs.product.title }}</b>
                                    </a>
                                </td>
                                <td class="text-left">{{ rs.comment }}</td>
                                <td class="text-left">{{ rs.status }}</td>
                                <td class="text-left">{{ rs.create_at }}</td>
                                <td class="text-left"><a class="btn btn-danger" href="/user/deletecomment/{{ rs.id }}"
                                                         onclick="return confirm('Will be DELETE! Are you sure?')">Delete</a>
                                </td>
                            </tr>
                        {% endfor %}
                    </table>

                </div>
            </div>

        </div>
    </div>
    </div>
{% endblock %}





{% comment %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Deneme</title>
</head>
<body>
    <h2>Django kurulum : python -m pip install</h2>
    <h2>Proje oluşturma : django-admin startproject mysite</h2>
    <h2>Server çalıştırma : python manage.py runserver</h2>
    <h2>App ekleme : python manage.py startapp home</h2>
    echo "# DjangoBlog" >> README.md
git init  //Bir kez
git add README.md   //Bir kez
git add .       //Her güncellemede
git commit -m "first commit"   //Her güncellemede
git remote add origin https://github.com/altuntasfth/DjangoBlog.git     //Bir kez
git push -u origin master    //Her güncellemede
git remote add origin https://github.com/altuntasfth/DjangoBlog.git
git push -u origin master
    <p>{{ text }}</p>
</body>
</html>{% endcomment %}

user/templates/user_contents.html
{% extends "homebase.html" %}

{% block title %}{{ profile.user_name }} Profile{% endblock %}
{% block keywords %}{{ setting.keywords }}{% endblock %}
{% block description %}{{ setting.description }}{% endblock %}
{% block head %}
    <link rel="shortcut icon" type="image/x-icon" href="{{ setting.icon.url }}"/>
{% endblock %}

{% block content %}
    {% load static %}
    <div class="section">
        <div class="container">
            <div class="row mb-4">
                <div class="col-md-6">
                    <h1>User Comments</h1>
                </div>
            </div>

            <div class="row blog-entries">
                <div class="col-md-2">
                    {% include "user_panel.html" %}
                </div>
                <div class="col-md-10 ">

                    <table class="table-active table">
                        <tr>
                            <th class="text-left">Image</th>
                            <th class="text-left">Title</th>
                            <th class="text-left">Category</th>
                            <th class="text-left">Gallery</th>
                            <th class="text-left">Status</th>
                            <th class="text-left">Date</th>
                        </tr>
                        {% for rs in contents %}
                            <tr>
                                <td class="text-left"><img src="{{ rs.image.url }}" style="height: 30px;"></td>
                                <td class="text-left">
                                    <a href="/product/{{ rs.id }}/{{ rs.slug }}">
                                        <b>{{ rs.title }}</b>
                                    </a>
                                </td>
                                <td class="text-left">{{ rs.category }}</td>
                                <td class="text-left">
                                    <a href="javascript:;" onclick="window.open('/user/contentaddimage/{{ rs.id }}', 'gallery', 'height=600, width=800, top=50, left=150')">
                                        <img src="{% static '' %}images/image_gallery.png" height="100">
                                    </a>
                                </td>
                                <td class="text-left">{{ rs.status }}</td>
                                <td class="text-left">{{ rs.create_at }}</td>
                                <td class="text-left"><a class="btn btn-danger" href="/user/contentedit/{{ rs.id }}">Edit</a>
                                <td class="text-left"><a class="btn btn-danger" href="/user/contentdelete/{{ rs.id }}"
                                                         onclick="return confirm('Will be DELETE! Are you sure?')">Delete</a>
                                </td>
                            </tr>
                        {% endfor %}
                        <tr>
                            <th class="text-left">
                                <a href="/user/addcontent" class="btn btn-primary">Add Blog</a>
                            </th>
                        </tr>
                    </table>

                </div>
            </div>

        </div>
    </div>
    </div>
{% endblock %}





{% comment %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Deneme</title>
</head>
<body>
    <h2>Django kurulum : python -m pip install</h2>
    <h2>Proje oluşturma : django-admin startproject mysite</h2>
    <h2>Server çalıştırma : python manage.py runserver</h2>
    <h2>App ekleme : python manage.py startapp home</h2>
    echo "# DjangoBlog" >> README.md
git init  //Bir kez
git add README.md   //Bir kez
git add .       //Her güncellemede
git commit -m "first commit"   //Her güncellemede
git remote add origin https://github.com/altuntasfth/DjangoBlog.git     //Bir kez
git push -u origin master    //Her güncellemede
git remote add origin https://github.com/altuntasfth/DjangoBlog.git
git push -u origin master
    <p>{{ text }}</p>
</body>
</html>{% endcomment %}

user/templates/user_panel.html
<div class="col-md-3 section-title">
    <h3 class="title">Panel</h3>
    <ul class="navbar-nav mx-auto">
        <li class="nav-item"><a href="/user" class="nav-link">Account</a></li>
        <li class="nav-item"><a href="/user/contents" class="nav-link">Blog</a></li>
        <li class="nav-item"><a href="/user/comments" class="nav-link">Comments</a></li>
        <li class="nav-item"><a href="#" class="nav-link">Favorites</a></li>
        <li class="nav-item"><a href="/logout" class="nav-link">Logout</a></li>
    </ul>
</div>

user/templates/user_update.html
{% extends "homebase.html" %}

{% block title %}{{ profile.user_name }} Profile{% endblock %}
{% block keywords %}{{ setting.keywords }}{% endblock %}
{% block description %}{{ setting.description }}{% endblock %}
{% block head %}
    <link rel="shortcut icon" type="image/x-icon" href="{{ setting.icon.url }}"/>
{% endblock %}


{% block content %}
    <div class="section">
        <div class="container">
            <div class="row mb-4">
                <div class="col-md-6">
                    <h1>User Profile</h1>
                </div>
            </div>

            <div class="row blog-entries">

                {% include "user_panel.html" %}

                <div class="col-md-9 ">

                        <div class="media">
                            <img src="{{ user.userprofile.image.url }}" style="height: 150px; border-radius: 45px">
                        </div>
                        <form method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            <fieldset class="form-group">
                                {{ user_form.as_p }}
                                {{ profile_form.as_p }}
                            </fieldset>
                            <div class="form-group">
                                <button class="btn btn-danger" type="submit">Update</button>
                            </div>
                        </form>

                </div>
            </div>

        </div>
    </div>
    </div>
{% endblock %}





{% comment %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Deneme</title>
</head>
<body>
    <h2>Django kurulum : python -m pip install</h2>
    <h2>Proje oluşturma : django-admin startproject mysite</h2>
    <h2>Server çalıştırma : python manage.py runserver</h2>
    <h2>App ekleme : python manage.py startapp home</h2>
    echo "# DjangoBlog" >> README.md
git init  //Bir kez
git add README.md   //Bir kez
git add .       //Her güncellemede
git commit -m "first commit"   //Her güncellemede
git remote add origin https://github.com/altuntasfth/DjangoBlog.git     //Bir kez
git push -u origin master    //Her güncellemede
git remote add origin https://github.com/altuntasfth/DjangoBlog.git
git push -u origin master
    <p>{{ text }}</p>
</body>
</html>{% endcomment %}